"""Per-node k7 agent (spec 18g).

Runs as a DaemonSet (``k7-agent``, kube-system) on every node, reusing the
``k7-api:local`` image with an overridden command
(``uvicorn k7.api.agent:app``). It exposes ONLY the node-local operations
that the centralized k7-api pod cannot perform for sandboxes on other
nodes:

- ``POST /agent/v1/vm/{pause,resume,fork,lookup}`` — thin wrappers over the
  ``K7Core`` k7d helpers (the k7d daemon socket, containerd socket, and
  crictl are all node-local).
- ``GET /agent/v1/storage`` — node storage-pool utilization (kfd LVM
  thin-pool via ``lvs``, k7d disks pool via ``df``).

Auth: every request must carry the shared agent token (header
``X-K7-Agent-Token``) generated by the install playbook and distributed to
``/etc/k7/agent_token`` on every node. A CiliumNetworkPolicy additionally
restricts pod-originated ingress to the k7-api pod. Requests without a
valid token are rejected — never served.
"""

import json
import os
import secrets
import subprocess

from fastapi import Depends, FastAPI, Header, HTTPException, Request, status
from fastapi.responses import JSONResponse

from .. import __version__
from ..core.core import K7Core

app = FastAPI(title="K7 Node Agent", version=__version__)

AGENT_TOKEN_FILE = os.getenv("K7_AGENT_TOKEN_FILE", "/etc/k7/agent_token")
KATA_VG = os.getenv("K7_KATA_VG", "kata-vg")
K7D_DISKS_DIR = os.getenv("K7D_DISKS_DIR", "/var/lib/k7d/disks")


def _load_agent_token() -> str:
    """Read the shared agent token — unreadable/empty is a deployment bug
    and must fail loudly (a silent 401 would be misdiagnosed as a bad
    caller token)."""
    try:
        with open(AGENT_TOKEN_FILE) as f:
            token = f.read().strip()
    except OSError as e:
        raise HTTPException(
            status_code=500,
            detail=(
                f"agent token {AGENT_TOKEN_FILE} is unreadable ({e}) — the install playbook "
                "provisions it on every node; re-run `k7 install`"
            ),
        )
    if not token:
        raise HTTPException(status_code=500, detail=f"agent token {AGENT_TOKEN_FILE} is empty — re-run `k7 install`")
    return token


async def verify_agent_token(x_k7_agent_token: str | None = Header(None)):
    if not x_k7_agent_token or not secrets.compare_digest(x_k7_agent_token.strip(), _load_agent_token()):
        raise HTTPException(status_code=401, detail="Invalid or missing agent token")


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):  # type: ignore[override]
    # Fail loud WITH the message — the k7-api forwarder surfaces it verbatim.
    return JSONResponse(
        content={"error": {"code": "InternalServerError", "message": str(exc)}},
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
    )


@app.get("/health")
async def health():
    return {"status": "healthy", "node": os.environ.get("K7_NODE_NAME", "")}


def _required_name(body: dict | None) -> tuple[str, str]:
    body = body or {}
    name = body.get("name")
    if not name or not isinstance(name, str):
        raise HTTPException(status_code=400, detail="name is required")
    return name, body.get("namespace", "default")


@app.post("/agent/v1/vm/pause", dependencies=[Depends(verify_agent_token)])
async def vm_pause(body: dict | None = None):
    name, namespace = _required_name(body)
    result = await K7Core().pause_sandbox(name=name, namespace=namespace, snapshot_name=(body or {}).get("snapshot"))
    return result.to_dict()


@app.post("/agent/v1/vm/resume", dependencies=[Depends(verify_agent_token)])
async def vm_resume(body: dict | None = None):
    name, namespace = _required_name(body)
    result = await K7Core().resume_sandbox(name=name, namespace=namespace)
    return result.to_dict()


@app.post("/agent/v1/vm/fork", dependencies=[Depends(verify_agent_token)])
async def vm_fork(body: dict | None = None):
    name, namespace = _required_name(body)
    new_name = (body or {}).get("new_name")
    if not new_name or not isinstance(new_name, str):
        raise HTTPException(status_code=400, detail="new_name is required")
    result = await K7Core().fork_sandbox(
        source_name=name,
        new_name=new_name,
        namespace=namespace,
        snapshot_name=(body or {}).get("snapshot"),
    )
    return result.to_dict()


@app.post("/agent/v1/vm/lookup", dependencies=[Depends(verify_agent_token)])
async def vm_lookup(body: dict | None = None):
    name, namespace = _required_name(body)
    return await K7Core().lookup_k7d_vm(name, namespace)


# ---------------------------------------------------------------------------
# Node storage-pool utilization (spec 18g part 2 / 18f issue 5 leftover).
# ---------------------------------------------------------------------------


def _run(cmd: list[str]) -> str:
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30, check=False)
    if result.returncode != 0:
        raise HTTPException(
            status_code=500,
            detail=f"{' '.join(cmd)} failed on node {os.environ.get('K7_NODE_NAME', '')}: {result.stderr.strip()}",
        )
    return result.stdout


def _kata_thinpool() -> dict:
    """kfd thin-pool utilization via ``lvs`` (needs a privileged container
    with /dev hostPath-mounted — the DaemonSet provides both)."""
    out = _run(["lvs", "--reportformat", "json", "--units", "b", "--nosuffix", KATA_VG])
    lvs = json.loads(out)["report"][0]["lv"]
    pools = [lv for lv in lvs if lv["lv_attr"].startswith("t")]
    if not pools:
        raise HTTPException(status_code=500, detail=f"no thin pool LV found in VG {KATA_VG} (lvs returned {lvs})")
    lv = pools[0]
    return {
        "vg": KATA_VG,
        "lv": lv["lv_name"],
        "size_bytes": int(float(lv["lv_size"])),
        "data_percent": float(lv["data_percent"]),
        "metadata_percent": float(lv["metadata_percent"]),
    }


def _k7d_disks() -> dict:
    """k7d disks-pool utilization via ``df`` on the hostPath-mounted
    /var/lib/k7d/disks XFS loopback mount."""
    if not os.path.isdir(K7D_DISKS_DIR):
        raise HTTPException(status_code=500, detail=f"{K7D_DISKS_DIR} not found — is the k7d backend installed?")
    out = _run(["df", "--output=size,used,avail", "--block-size=1", K7D_DISKS_DIR])
    size, used, avail = out.splitlines()[1].split()
    return {
        "path": K7D_DISKS_DIR,
        "size_bytes": int(size),
        "used_bytes": int(used),
        "avail_bytes": int(avail),
        "used_percent": round(100.0 * int(used) / int(size), 2) if int(size) else 0.0,
    }


@app.get("/agent/v1/storage", dependencies=[Depends(verify_agent_token)])
async def storage():
    return {"kata_thinpool": _kata_thinpool(), "k7d_disks": _k7d_disks()}
